# Generated by Django 5.2.4 on 2025-07-24 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.amount')),
            ],
        ),
    ]
