# Generated by Django 5.2.4 on 2025-07-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voucher',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
